angular.module('ui.directives',[
	'ui.directives.select2',
	'ui.directives.date',
	'ui.directives.jq',
	'ui.directives.keypress',
	'ui.directives.linky',
	'ui.directives.mask',
	'ui.directives.remove',
	'ui.directives.reset',
	'ui.directives.scrollfix',
	'ui.directives.showhide'
]);
