// Generated by CoffeeScript 1.3.3

/*
Angular date widget that wraps around jQuery UI date widget.
*/


(function() {

  angular.module('ui.directives').directive('uiDate', function() {
    return {
      require: '?ngModel',
      link: function($scope, element, attrs, ngModelCtrl) {
        var originalRender, updateModel, updateOptions;
        updateModel = function(value, picker) {
          return $scope.$apply(function() {
            return ngModelCtrl.$setViewValue(element.datepicker("getDate"));
          });
        };
        updateOptions = function(options) {
          var usersOnSelectHandler;
          if (options.onSelect != null) {
            usersOnSelectHandler = options.onSelect;
            return options.onSelect = function(value, picker) {
              updateModel(value);
              return usersOnSelectHandler(value, picker);
            };
          } else {
            return options.onSelect = updateModel;
          }
        };
        if (ngModelCtrl != null) {
          originalRender = ngModelCtrl.$render;
          ngModelCtrl.$render = function() {
            originalRender();
            return element.datepicker("setDate", ngModelCtrl.$viewValue);
          };
        }
        return attrs.$observe('uiDate', function(value) {
          var options;
          options = {};
          if (angular.isObject(value)) {
            options = value;
          }
          if (ngModelCtrl != null) {
            updateOptions(options);
          }
          return element.datepicker(options);
        });
      }
    };
  });

}).call(this);
