// Generated by CoffeeScript 1.3.3

/*
A masked input widget - allows you to specify a mask of what characters you can enter into the input element.
*/


(function() {

  angular.module('ui.directives').directive('uiMask', function() {
    return {
      require: 'ngModel',
      link: function($scope, element, attrs, controller) {
        var mask, updatePlaceholder;
        mask = null;
        updatePlaceholder = function() {
          if (!(attrs.placeholder != null)) {
            return element.attr('placeholder', mask.replace(/9/g, '_'));
          }
        };
        controller.$render = function() {
          var value, _ref;
          value = (_ref = controller.$viewValue) != null ? _ref : '';
          element.val(value);
          if (mask != null) {
            element.mask(mask);
          }
          return updatePlaceholder();
        };
        attrs.$observe('uiMask', function(maskValue) {
          mask = maskValue;
          return controller.$render();
        });
        controller.$parsers.push(function(value) {
          var isValid;
          isValid = element.data('mask-isvalid');
          controller.$setValidity('mask', isValid);
          if (isValid) {
            return element.mask();
          } else {
            return null;
          }
        });
        return element.bind('keyup', function() {
          return $scope.$apply(function() {
            return controller.$setViewValue(element.mask());
          });
        });
      }
    };
  });

}).call(this);
